// src/lib/Swipable.svelte
<script lang="ts">
import type { Snippet } from "svelte";

interface Props {
	class?: string;
	onswipe: (ev: { deltaX: number }) => void;
	children: Snippet;
}
const { class: className = "", onswipe, children }: Props = $props();
let point = $state({ x: 0, y: 0 });

function handleTouchStart(ev: TouchEvent) {
	if (ev.targetTouches.length !== 1) return ev.preventDefault();
	const touch = ev.targetTouches.item(0)!;
	point.x = touch.pageX;
	point.y = touch.pageY;
}
function handleTouchEnd(ev: TouchEvent) {
	if (ev.changedTouches.length !== 1) return ev.preventDefault();
	const touch = ev.changedTouches.item(0)!;
	const deltaX = touch.pageX - point.x;
	const deltaY = touch.pageY - point.y;
	if (deltaX === 0 || Math.abs(deltaX) < Math.abs(deltaY)) return;
	onswipe({ deltaX });
}
</script>

<div class={className} ontouchstart={handleTouchStart} ontouchend={handleTouchEnd}>
	{@render children()}
</div>

// src/components/Swipable.tsx
import { HTMLProps, TouchEventHandler, useCallback, useImperativeHandle, useRef } from "react";

export const enum SwipeDir {
  LEFT = -1,
  RIGHT = 1,
}

export type OnSwipe = (dir: SwipeDir) => void;

interface Props extends HTMLProps<HTMLDivElement> {
  onSwipe: OnSwipe;
}

export function Swipable({ onSwipe, children, ...props }: Props) {
  const startPos = useRef<{ x: number; y: number }>();
  const onTouchStart = useCallback<TouchEventHandler>((ev) => {
    if (ev.targetTouches.length !== 1) {
      return ev.preventDefault();
    }
    const { pageX, pageY } = ev.targetTouches.item(0);
    startPos.current = { x: pageX, y: pageY };
  }, []);

  const onTouchEnd = useCallback<TouchEventHandler>(
    (ev) => {
      if (!startPos.current || ev.changedTouches.length !== 1) return;
      const { pageX, pageY } = ev.changedTouches.item(0);
      const deltaX = startPos.current.x - pageX;
      const deltaY = startPos.current.y - pageY;

      if (Math.abs(deltaY) > Math.abs(deltaX)) return;
      if (deltaX < 5) onSwipe(SwipeDir.LEFT);
      if (deltaX > 5) onSwipe(SwipeDir.RIGHT);
    },
    [onSwipe]
  );
  return (
    <div {...props} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}>
      {children}
    </div>
  );
}
